### ISSUE TITLE
🐞: Background in `about.html` disappears

### ISSUE THREAD

**Issue by nandgator** [sarathsajan/cross-path-alert#10]
The background in [`about.html`](https://github.com/sarathsajan/cross-path-alert/blob/master/templates/about.html) disappears after a few minutes.
- Initially (see the time in screenshot)
![Screenshot from 2020-03-31 11-56-58](https://user-images.githubusercontent.com/38415384/77994635-fba52d80-7347-11ea-9580-8d196c7dd12f.png)
- After a few minutes, coming back to this tab.
![Screenshot from 2020-03-31 12-01-46](https://user-images.githubusercontent.com/38415384/77994650-01027800-7348-11ea-807c-2f0ae4f883f0.png)

**Comment by bestin-07** [comment]
THANKS FOR THE FEEDBACK

**Comment by sarathsajan** [comment]
experimental branch created to address that issue
