### ISSUE TITLE
Logout using back button

### ISSUE THREAD

**Issue by bestin-07** [sarathsajan/cross-path-alert#17]
User is able to logout from dashboard using back button.
![Screenshot_20200404_174135](https://user-images.githubusercontent.com/57059472/78450457-4ef6e300-769c-11ea-8155-f59395df4258.jpg)
But by doing so the logout button is still present in the navbar.
![Screenshot_20200404_174143](https://user-images.githubusercontent.com/57059472/78450486-6f26a200-769c-11ea-9c4c-6de4d3dd922c.jpg)

It is only until that button is pressed, ' your now logged out' message is shown.
![Screenshot_20200404_174206](https://user-images.githubusercontent.com/57059472/78450499-89f91680-769c-11ea-80d6-87e9a6828050.jpg)

**Comment by sarathsajan** [comment]
When you press the back button you are just going back to the previous page and not getting logged out. Hence there is no 'you have been logged out' message and the logout button is still visible in the NavBar
